#################### 🚧 WARNING: READ THIS BEFORE USING THIS FILE 🚧 ####################
#
#
#
# IF YOU DON'T KNOW WHAT YOU'RE DOING, YOU CAN EASILY LEAK SECRETS BY USING A
# `pull_request_target` WORKFLOW INSTEAD OF `pull_request`! SERIOUSLY, DO NOT
# BLINDLY COPY AND PASTE THIS FILE WITHOUT UNDERSTANDING THE FULL IMPLICATIONS
# OF WHAT YOU'RE DOING! WE HAVE TESTED THIS FOR OUR OWN USE CASES, WHICH ARE
# NOT NECESSARILY THE SAME AS YOURS! WHILE WE AREN'T EXPOSING ANY OF OUR SECRETS,
# ONE COULD EASILY DO SO BY MODIFYING OR ADDING A STEP TO THIS WORKFLOW!
#
#
#
#################### 🚧 WARNING: READ THIS BEFORE USING THIS FILE 🚧 ####################

name: Preview Deployment
on:
  pull_request_target:
    paths:
      - "sites/www/**"

jobs:
  deploy-preview:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
      deployments: write
    name: Deploy www Preview to Cloudflare Pages
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}

      # Run a build step here
      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: pnpm

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: 8
          run_install: false

      - name: Install dependencies
        run: pnpm i --frozen-lockfile

      - name: Build site
        run: pnpm -F www build

      - name: Deploy to Cloudflare Pages
        uses: AdrianGonz97/refined-cf-pages-action@fix/workflow_run
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          accountId: ${{ secrets.CF_ACCOUNT_ID }}
          projectName: cf-monorepo-test-site
          directory: ./.svelte-kit/cloudflare
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          workingDirectory: sites/www
          deploymentName: www (Preview)

  trusted-preview-www2:
    if: ${{ github.event.pull_request.author_association == 'MEMBER' || github.event.pull_request.author_association == 'COLLABORATOR' || github.event.pull_request.author_association == 'OWNER' }}
    runs-on: ubuntu-latest
    name: Deploy www2 Preview to Cloudflare Pages (admin)
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}
      - uses: pnpm/action-setup@v4
        with:
          version: 8
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: pnpm

      # Run a build step here if your project requires
      - name: Install dependencies
        run: pnpm install

      - name: Build site
        run: pnpm -F www2 build

      - name: Deploy to Cloudflare Pages
        id: cloudflare-pages-deploy
        uses: AdrianGonz97/refined-cf-pages-action@fix/workflow_run
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          accountId: ${{ secrets.CF_ACCOUNT_ID }}
          projectName: cf-monorepo-test-site2
          directory: ./.svelte-kit/cloudflare
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          workingDirectory: sites/www2
          deploymentName: www2 (Preview)

  untrusted-preview:
    if: ${{ !(github.event.pull_request.author_association == 'MEMBER' || github.event.pull_request.author_association == 'COLLABORATOR' || github.event.pull_request.author_association == 'OWNER') }}
    environment: Preview
    runs-on: ubuntu-latest
    name: Deploy Preview to Cloudflare Pages
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}
      - uses: pnpm/action-setup@v4
        with:
          version: 8
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: pnpm

      # Run a build step here if your project requires
      - name: Install dependencies
        run: pnpm install

      - name: Build site
        run: pnpm -F www build

      - name: Deploy to Cloudflare Pages
        id: cloudflare-pages-deploy
        uses: AdrianGonz97/refined-cf-pages-action@fix/workflow_run
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          accountId: ${{ secrets.CF_ACCOUNT_ID }}
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          projectName: cf-monorepo-test-site
          directory: ./.svelte-kit/cloudflare
          workingDirectory: sites/www
          deploymentName: Preview

      - name: Print
        run: echo "alias - ${{steps.cloudflare-pages-deploy.outputs.alias}}"
