name: Production Deployment
on:
  push:
    branches:
      - master
    paths:
      - "sites/www/**"

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    name: Publish to Cloudflare Pages
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - uses: actions/setup-node@v3
        with:
          node-version: 18

      # PNPM Store cache setup
      - name: Get pnpm store directory
        id: pnpm-cache
        run: |
          echo "pnpm_cache_dir=$(pnpm store path)" >> $GITHUB_OUTPUT
      - name: Setup pnpm cache
        uses: actions/cache@v3
        with:
          path: ${{ steps.pnpm-cache.outputs.pnpm_cache_dir }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      # Run a build step here if your project requires
      - name: Install dependencies
        run: pnpm install

      - name: Build site
        run: pnpm -F www build

      - name: Deploy to Cloudflare Pages
        uses: AdrianGonz97/cf-pages-action@hb
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          accountId: ${{ secrets.CF_ACCOUNT_ID }}
          projectName: cf-monorepo-test-site
          directory: ./.svelte-kit/cloudflare
          deploymentName: Production
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
          workingDirectory: sites/www
          wranglerVersion: "3"
