name: Production Deployment
on:
  push:
    branches:
      - master
    paths:
      - "sites/www/**"

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    name: Publish to Cloudflare Pages
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 8
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: pnpm

      # Run a build step here if your project requires
      - name: Install dependencies
        run: pnpm install

      - name: Build site
        run: pnpm -F www build

      - name: Deploy to Cloudflare Pages
        uses: AdrianGonz97/refined-cf-pages-action@fix/workflow_run
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          apiToken: ${{ secrets.CF_API_TOKEN }}
          accountId: ${{ secrets.CF_ACCOUNT_ID }}
          projectName: cf-monorepo-test-site
          workingDirectory: sites/www
          directory: ./.svelte-kit/cloudflare
          deploymentName: Production
